# Generated by Django 4.1.2 on 2022-11-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_product_quantity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='Category',
            table='Categories'
        )
    ]
