# Generated by Django 4.2.5 on 2023-09-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0005_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruit', 'Fruit'), ('Meat', 'Meat'), ('Vegan', 'Vegan'), ('Seasoning', 'Seasoning'), ('Sweet', 'Sweet'), ('Drink', 'Drink')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
